[점심 뭐 먹지 미션 Step 1] 해온(백솔비) 미션 제출합니다. (#38)
* chore: 리액트 및 styled-components 설치

* docs: 기능 목록 작성

* docs: README 작성

* chore: 음식점 mock 데이터 구현

* feat: 음식점 컴포넌트 생성

* design: 음식점 컴포넌트 스타일링

* fix: 번들 에러 개선

`Uncaught SyntaxError: Unexpected token '<'` fixed

* feat: 모달창 구현

* design: 모달창 스타일링

* fix: App.test.js 에러 개선

`expect(...).toBeInTheDocument is not a function` error fixed

* design: 커서 포인터 추가

* feat: 모달창 여닫기 기능 구현

+ 링크 클릭시 해당 페이지로 이동하는 기능 구현
- design: 새로고침시 이미지 눌림 현상 개선

* feat: 음식점 클릭시 해당 음식점 정보가 담긴 모달창을 보여주는 기능 구현

* feat: 셀렉트 박스 구현

* feat: 카테고리 선택시 해당 카테고리의 음식점 목록만 보여주는 기능 구현

* feat: 이름순/거리순 선택시 음식점을 이름순/거리순으로 정렬하는 기능 구현

* feat: 헤더 영역 구현

* refactor: 음식점 초깃값 이름순으로 정렬

* refactor: restaurantStore 삭제

* feat: 새로고침시에도 선택된 옵션이 사라지지 않는 기능 구현

* rename: 컴포넌트 파일명의 머리글자 대문자로 변경

* refactor: any 타입 삭제

* refactor: interface를 이용한 타입 선언 및 분리

* refactor: 필요없는 코드 삭제 및 상수화

* refactor: 프로퍼티, state명 변경 및 태그 변경

* docs: README 수정

이미지 첨부, 제목 가운데 정렬

* refactor: 함수 분리 및 이름 축약

* delete: 사용하지 않는 파일 삭제

* docs: README 수정

레벨1 -> 레벨2 변경

* chore: 자동 배포 설정

* fix: 자동 배포 오류 개선

* fix: 자동 배포 오류 개선

* 모든 캐시 삭제

* fix: 이미지 렌더링 오류 개선

* design: 스크롤 숨김

* docs: README 수정

앱 바로가기 링크 첨부

* fix: 앱 처음 실행시 음식점 목록을 두 번 클릭해야 모달이 보이는 오류 개선

타입 가드로 return을 사용해 null값일 경우 렌더링을 안 해서 생기는 문제
=> return 대신 && 연산자를 사용하여 타입 가드

* chore: homepage 이름 변경

* chore: react script 설치

---------

Co-authored-by: Dain Lee <feb.dain@gmail.com>